### ISSUE TITLE
overflow error, slow performance

### ISSUE THREAD

**Issue by emdete** [cbdevnet/xelflut#7]
> Written directly against XRender so it should probably be pretty fast.

i detected the opposite while i expected the same... 

when running via localhost i get overrun errors. i modified the code to ignore this state and the program works fine now. but it is incredible slow compared to the java version from https://github.com/defnull/pixelflut

what's wrong?

**Comment by cbdevnet** [comment]
Don't know really, never benchmarked it - which client did you use?

**Comment by cbdevnet** [comment]
Just a quick test seems to confirm it's pretty fast - if you crank up the pixel-per-frame limit (the `-l` command line option), which is 50 by default. To get around the overrun errors (really just a side effect of the client exceeding the set limits and `xelflut` enforcing them by disconnecting), I've added a 'nice' mode (argument `-n`) which simply ignores pixels after the per-frame limit has been exhausted. Since the message was pretty useless, I've changed it to be more precise.

**Comment by cbdevnet** [comment]
I've added an unsafe mode (argument `-u`), disregarding duplicate connection and limit checks for performance testing.
I've also added a display for average updates (changed pixels per frame), which when testing on my pretty low-end notebook (T400, Intel GM45 Chipset), running at 25 frames per second, hovers at around 3500 updates per frame for a single client, rising to just shy of 6000 with two clients (a Python script generating a random snake).

I don't know about the numbers of the Java server, but if you'd try it again, I'd love to get feedback :)

**Comment by cbdevnet** [comment]
Upon further reflection, I've changed the 'nice' mode to a generic 'Limit enforcer policy' option (`-e`), which allows you to select from `limit` (default), `disconnect`, `ignore` and `none`.

**Comment by cbdevnet** [comment]
Testing with a machine with more graphics firepower (GeForce GTX 560), I was unable to max out the server due to my simple Python client hogging the client machine's CPUs. With 7 clients on 7 different machines all running at 100%, the server did 30000 updates per frame with the CPU barely at 30%.
Closing this as the issue seems to have disappeared ;)

Minor update, using some beefy clients I was able to max out performance on that particular machine, at about 42000 updates per frame at 25 fps. At that speed, the `Xorg` process hogs one core at 100%, with `xelflut` using 40% of a second core. I guess further optimization would have to be done on Xorg (or by switching from XRender to some faster interface, though I don't really have the numbers on those) ;)

**Comment by emdete** [comment]
ah, ok, my fault, i had a wrong understanding on how the limiting works. `-u` opens the door for stats:

percent | process
--|--
98,0 | python2
70,8 | xelflut
62,1 | Xorg

so while my py-client is at its limits the xelflut is next but the X even lower. i get max 10499.609414 updates with 25fps. so next step would be to replace the py-client with something less resource hungry. thanks for your work & reply!

**Comment by cbdevnet** [comment]
Oh, to amend the previous performance measurements (which were kinda buggy since the GPU wasn't actually used for rendering): when taking `python` out of the consideration by just creating a huge file with data and pumping it onto the socket with `nc`, I can get to 200 000 updates per frame at 25 fps (making about 5 MP/s) before running against a CPU wall.
